name = "squirrel"
version = "1.3.2"
description = "ğŸ¿ï¸ Type safe SQL in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "squirrel" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
eval = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
mug = ">= 1.1.0 and < 2.0.0"
glam = ">= 2.0.1 and < 3.0.0"
justin = ">= 1.0.1 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
term_size = ">= 1.0.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
pgo = ">= 0.14.0 and < 1.0.0"
decode = ">= 0.2.0 and < 1.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
tom = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.1.8 and < 2.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
gleam_pgo = ">= 0.13.0 and < 1.0.0"
