name = "squirrel"
version = "4.5.0"
description = "ğŸ¿ï¸ Type safe SQL in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "squirrel" }
gleam = ">= 1.11.0"

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
eval = ">= 1.0.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
glam = ">= 2.0.1 and < 3.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
non_empty_list = ">= 2.1.0 and < 3.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
term_size = ">= 1.0.1 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
tote = ">= 1.0.2 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"
glexer = ">= 2.1.0 and < 3.0.0"
mug = ">= 3.0.0 and < 4.0.0"
pog = ">= 4.1.0 and < 5.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.8 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
